[project]
name = "now-playing-deployment-mode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyring>=25.6.0",
    "pyside6>=6.9.2",
    "requests>=2.32.5",
    "spotipy>=2.25.1",
]
